#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  application (web-frontend for Haiku / Automatoetry)
#
#  Copyright 2013 Tobias Radloff <mail@tobias-radloff.de>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#


from __future__ import division, absolute_import
import os

# lokal oder Openshift?
if "OPENSHIFT_PYTHON_DIR" in os.environ:
	RUNS_ON_OPENSHIFT = True
else:
	RUNS_ON_OPENSHIFT = False

# Virtual Environment fuer Openshift
if RUNS_ON_OPENSHIFT:
	virtenv = os.environ["OPENSHIFT_PYTHON_DIR"] + "/virtenv/"
	os.environ["PYTHON_EGG_CACHE"] = os.path.join(virtenv, "lib/python2.6/site-packages")
	virtualenv = os.path.join(virtenv, "bin/activate_this.py")
	try:
		execfile(virtualenv, dict(__file__=virtualenv))
	except IOError:
		pass

# Zusaetzliche Module erst ab hier importieren wg. Openshift virtenv
import web
import json
import tempfile
from automatoetry import AutoPoemSpecimen
from copy import deepcopy

# Initialisierungsvariablen fuer web.py
urls = ("/", "start", "/do", "automatoetry")
render = web.template.render(os.path.abspath(os.path.dirname(__file__)) + "/templates/")
web.config.debug = True #DEBUG

if RUNS_ON_OPENSHIFT:
	application = web.application(urls, globals()).wsgifunc()
else:
	app = web.application(urls, globals()) # erzeugt ImportError, falls kein Symlink application.py -> application existiert

# Session-Parameter
web.config.session_parameters.cookie_name = "haiku_session_id"
tmpDir = tempfile.mkdtemp()
if web.config.get('_session') is None:
	session = web.session.Session(app, web.session.DiskStore(tmpDir))
	web.config._session = session
else:
	session = web.config._session
print "application: Tempdir ist", tmpDir #DEBUG


class start:
	u"""Definiert Formular und GET- und POST-Methoden fuer die
		Startwebseite des Projekts, auf der der User den Genotyp fuer
		Generation 1 bestimmt. Das zugehoerige Template ist
		"templates/start.html".
	"""
	# @TODO: Auswahlkaestchen fuer die Developfkt. hinzufuegen
	form = web.form.Form(
		web.form.Textbox(
			"seedword",
			web.form.notnull,
			size = 19,
			class_ = "textfield",
			description = "Startwort:"
		),
		web.form.Button(
			"Neues Zufallswort",
			id = "newSeedword",
			class_ = "button"
		),
		web.form.Textbox(
			"genes",
			web.form.notnull,
			web.form.regexp(r"^[a-z ]*$", "Bitte nur Kleinbuchstaben"),
			web.form.regexp(r"^[a-z]{5} [a-z]{7} [a-z]{5}$", "Gene muessen 5, 7, 5 Zeichen enthalten, jeweils durch Leerzeichen getrennt"), #
			size = 19,
			maxlength = 19,
			class_ = "textfield",
			description = "Gene:"
		),
		web.form.Button(
			"Neue Gene",
			id = "newGenes",
			class_ = "button"
		),
		web.form.Button(
			"Los",
			class_ = "los"
		)
	)


	def GET(self):
		u"""Gibt das Formular fuer Gene und Seedwort zurueck, befuellt
			mit Zufallswerten.
		"""
		session.kill() # erzeugt automatisch neue Session
		tmpHaiku = AutoPoemSpecimen()
		f = self.form()
		f["seedword"].set_value(tmpHaiku.getGenotype()[0])
		f["genes"].set_value(tmpHaiku.getGenotype()[1])
		return render.start(f)


	def POST(self):
		u"""Wird von den Buttons auf "templates/start.html" aufgerufen.
			Je nach Aufrufer wird unterschiedlich verfahren:
			- Neues Seedwort / Neue Gene: Funktion gibt neue
			Zufallswerte zurueck
			- Los-Button (Submit): Funktion erzeugt haiku mit den
			Werten aus dem Formular neu und ruft Seite "do" auf.
		"""
		input = web.input()
		print "/ POST: input ist", input, "und die Session-ID lautet", session.session_id #DEBUG

		# "Los"-Button
		if "caller" not in input:
			f = self.form()
			if not f.validates():
				return render.start(f)
			session.haiku = AutoPoemSpecimen(f.d.seedword, f.d.genes)
			raise web.seeother("do")

		# "Neu"-Button: neues Seedwort oder Gene zurueckgeben
		tmpPoem = AutoPoemSpecimen()
		if input["caller"] == "newSeedword":
			return tmpPoem.getRandomSeedword()
		elif input["caller"] == "newGenes":
			return tmpPoem.getRandomGenes()


class automatoetry:
	u"""Definiert GET- und POST-Methoden fuer die Hauptwebseite des
		Projekts, auf der der User zwischen den Kindern einer Generation
		entscheidet, welches sich weiter fortpflanzt. Das zugehoerige
		Template ist "templates/automatoetry.html".
	"""

	def GET(self):
		u"""Gibt Seedwort, Gene und Phaenotyp fuer Generation 1 zurueck
			(den Phaenotyp als Liste von Zeilen).
		"""
		if not "haiku" in session:
			raise web.seeother("/")
		print "/do GET: Hole Phaenotyp fuer Generation", session.haiku.getGeneration()
# @TODO: getPhenotype()-Aufruf in try: except HaikuError-Block einbetten. Problem: Wenn Fehler, wie gebe ich den an die Ajax-Fkt. weiter?
		phenotype = session.haiku.getPhenotype()
		return render.automatoetry(session.haiku.getGenotype()[0], session.haiku.getGenotype()[1], phenotype.split("\n"), session.haiku.getGeneration())
# @TODO: Hier sollte ich nicht den Phaenotypen mit uebergeben, damit die Seite erst mal laedt. Wenn ich den Phaenotypen per Ajax-Request nachfordere, erreiche ich, dass die Seite bei einem Wortschatz-Serverfehler nicht ausschließlich aus einer Fehlermeldung besteht. Andererseits sollte das Problem von alleine weggehen, sobald ich ein Header/Footer-Template verwende.


	def POST(self):
		u"""Erledigt POST-Requests. Sorgt fuer den Wechsel zur neuen
			Generation und gibt die zwei neue Kinder zurueck.
		"""
		input = web.input()
		print "/do POST: input ist:", input, "und das Session-Haiku lautet", session.haiku #DEBUG

		# Welches Kind wird neuer Elter?
		if input["child"] == "l":
			parent = session.haiku.getChildren()[0]
		elif input["child"] == "r":
			parent = session.haiku.getChildren()[1]
		else: # initialer Ajax-Aufruf
			parent = session.haiku

		# neue Kinder erzeugen
		children = parent.procreateN(2)
		for c in children:
			c.getPhenotype()
		if parent != session.haiku:
			session.haiku = parent

		# Daten im JSON-Format zurueckgeben
		data = [[c.getGenotype()[0], c.getGenotype()[1], c.getPhenotype().replace("\n", "<br/>")] for c in children]
		data.append(str(children[0].getGeneration()))
		return json.dumps(data)


if __name__ == '__main__':
	if RUNS_ON_OPENSHIFT:
		from wsgiref.simple_server import make_server
		httpd = make_server('localhost', 80, application)
		httpd.serve_forever()
	else: # starte lokal mit web.py
		app.run()
